$ Messages for the OpenCOMAL interpreter.
$quote "

$set Main
NewlocaleFailed "warning: Setting locale failed.\nwarning: Please check that the locale \"%s\" is supported and installed on your system.\nwarning: Falling back to the global locale (\"%s\").\n"
BadOpt "Unrecognised option: '-%c'\n"
Usage "usage: %s [-y] [-m <msg-catalog>] ...\n"
Copyright "(c) Copyright 1992-2002  Jos Visser <josv@osp.nl>"
Banner "OpenComal -- A free Comal implementation (version %s; %s; build %s)"
Built "             Built on %s at approximately %s"
Lic1 "OpenComal is licensed under the GNU General Public License (GPL) version 2"
Lic2 "(The GPL contains a very nice statement on WARRANTY; you might want to read it)"
ReqOp "Option -%c requires an operand\n"

$set CLoop
Escape "Escape"
HaltedPrompt "(halted)$ "

$set Exec
Stopped "OpenComal's warp engines answered full stop"
Sure "Are you sure? "
InputEsc "Escape from INPUT"

$set Misc
NotSaved "Latest changes have not yet been saved! Proceed? "
EnvUnsaved "Environment %s contains unsaved changes!"
Proceed "Proceed? "

$set Linux
No "No\n"
Yes "Yes\n"
