$ Messages for the OpenCOMAL interpreter.
$ This file must use the Latin-9 encoding,
$ even though the generated catalog will be installed in a utf8 locale.
$quote "

$set Main
NewlocaleFailed "rabhadh: Theip ar locale a roghadh.\nrabhadh: Ba cheart go mbeidís in ann an locale \"%s\" a úsáid ar do ríomhaire.\nrabhadh: Ag dul ar ais go dtí an príomh-locale (\"%s\").\n"
BadOpt "Modh mí-aithneach: '-%c'\n"
Usage "úsáid: %s [-dy] [-m <msg-catalog>] ...\n"
Copyright "             (c) Cóipcheart 1992-2002  Jos Visser <josv@osp.nl>"
Banner "OpenComal -- Clár Comal saor (eagrán %s; %s; déanamh %s)"
Built "             Athrú deireanach ar an "
Lic1 "Tá OpenComal ceadaithe faoin Ceadúnas Poiblí Ginereálta (GPL) eagrán a 3"
Lic2 "(Tá ráiteas iontach sa GPL faoi WARRANTY; is dócha gur ba mhaith leat é a léamh)"
ReqOp "Tá operand ag teastáil ar option -%c\n"

$set CLoop
HaltedPrompt "(stadtha)$ "

$set Exec
Stopped "D'fhreagair innealta warp OpenComal stad go leor"
Sure "An bhfuil tú cinnte? "
InputEsc "Éalú ó INPUT"
CantExit "Ní féidir EXIT i modh díreach (bain úsáid as BYE chun OpenCOMAL a fhágáil)"

$set Misc
NotSaved "Níl na hathraithe is déanaí sábháilte! Lean ar aghaidh? "
EnvUnsaved "Tá athraithe neamh-sábháilte i dtimpeallacht %s!"
Proceed "Lean ar aghaidh? "

$set UNIX
No "Ní hea\n"
Yes "Sea\n"

$set Scan
CurExec "an líne atá ag rith anois"
CurData "an líne DATA atá á úsáid"
StrucLine "líne structúir an clár"
InhibCon "Tar éis %s a athrú ní féidir leanúint"

$set Pars
SynErr "Earráid chomhréire"

$set Common
Escape "Éalú"
