$ Messages for the OpenCOMAL interpreter.
$quote "

$set Main
NewlocaleFailed "aire: Theip ar locale a roghadh.\naire: Ba cheart go mbeidís in ann an locale \"%s\" a úsáid ar do ríomhaire.\naire: Ag dul ar aghaidh to dtí an príomh-locale (\"%s\").\n"
BadOpt "Modh mí-aithneach: '-%c'\n"
Usage "úsáid: %s [y] ...\n"
Copyright "(c) Cóipcheart 1992-2002  Jos Visser <josv@osp.nl>"
Banner "OpenComal -- Clár Comal saor (eagrán %s; %s; déanamh %s)"
Built "             Déanta ar an %s timpeall %s"
Lic1 "Tá OpenComal ceadaithe faoi an Ceadúnas Poiblí Ginereálta (GPL) eagrán a 2"
Lic2 "(Tá ráiteas iontach sa GPL faoi WARRANTY; is dócha gur ba mhaith leat é a léamh)"
